version: '2'

services:
  app1-service:
    build: ./app1
    container_name: app1
    hostname: app1
    ports:
      - "8080:8080"
    volumes:
      - "./sample.json:/app/sample.json"
  app2-service:
    build: ./app2
    container_name: app2
    hostname: app2
    ports:
      - "9090:9090"
    depends_on:
      - app1
    links:
      - app1
